### ISSUE TITLE
issue: premium question's are different from the question's title

### ISSUE THREAD

**Issue by jha-om** [Edwardsoen/Leetcode-Premium-Unlocker#14] opened 2023-05-19 05:51 UTC
Hey @Edwardsoen, I know leetcode ui has been changed and u are fixing the issue's related to it, but one more issue I have noticed that the locked question show's the data of previous question.(for better clearity I have attached some screenshots related to it).
![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/94907651/aec3752c-bea9-47ed-bf67-d48d7b3f5b8c)
![image](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker/assets/94907651/abbd3d2d-8933-4ecf-9d28-2ecf625dd91e)

**In the attached screenshots, question data has to be of question no. 302(smallest rectangle enclosing black pixels) rather than of ques. no. 301(remove invalid parentheses).**

Take a look on this issue also and please fix it.

**Comment by Edwardsoen** [comment] 2023-05-19 14:51
confirmed and replicable, good catch. will fix next update

**Comment by Edwardsoen** [comment] 2023-05-19 15:50
lol this issue have been around since the beginning, i'm surprised no one mention this yet, i guess no one use this feature.

**Comment by Edwardsoen** [comment] 2023-05-19 18:20
Fixed in 0.5.3, let me know if you are still facing the same problem in 0.5.3

**Comment by jha-om** [comment] 2023-05-19 19:34
@Edwardsoen First of all thank u for addressing the issue, and just to confirm that 0.5.3 update has been rolled out or it will done later?

**Comment by Edwardsoen** [comment] 2023-05-19 19:43
it has been rolled out, its live on Firefox add ons or you can download it on github release page, but Google webstore require review and it usually takes a few days.

**Closed** 2023-05-25 16:01 UTC
